version: '3.8'

services:
  discord:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        JARGON_APP: discord
        JARGON_ENV: prod
      target: production
    env_file: ./config/.env
