version: '3.8'

services:
  discord:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
      args:
        KCJARGON_APP: discord
        KCJARGON_ENV: dev
    env_file: ../config/.env
    volumes:
      - ..:/workspace:cached
      - ../../jargonai:/jargonai
      - discord-bashhistory:/commandhistory
    command: sleep infinity
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  discord-bashhistory:
